
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';


//Banner
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST';
export const RECEIVE_BANNER_LIST = 'RECEIVE_BANNER_LIST';
